version: "2"
plugins:
  scalastyle:
    enabled: true
  duplication:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
exclude_patterns:
- ".idea/"